### ISSUE TITLE
Training my own model

### ISSUE THREAD

**Issue by frankpreel** [linto-ai/linto-desktoptools-hmg#1]
I've tried out the following documentation
`https://github.com/linto-ai/linto-desktoptools-hmg/wiki/Training-a-model`
But not able to generate my own model.

I've installed on linux Ubuntu 18.10 the HMG installer, create a project, put in a folder a (or several) vaw file (Signed 16 bit Little Endian, Fréquence 16000 Hz, Mono).
But when I try to generate the model, with default settings, the UI crashes with the following stack trace.

```
Traceback (most recent call last):
  File "interfaces/mainwindows.py", line 79, in on_project_updated
  File "interfaces/mainwindows.py", line 119, in open_manage_tab
  File "interfaces/manage.py", line 25, in __init__
  File "interfaces/manage.py", line 89, in present_sets
ZeroDivisionError: division by zero
Abandon (core dumped)
```

Did I mess something in the model generation steps?

**Comment by Lokhozt** [comment]
The issue comes from a zero division caused by a set being empty. Fixed by 0.9hotfix1.
